### PR TITLE
Some files updated to correct and improve the pdf file

### PR DESCRIPTION
**Pull request by MoeinSorkhei**
Hi,

We have made some changes to correct the mistakes and enhance the final pdf file. 

1. We are still unable to get the text and numbers bold in the pdf the `\textbf` and `\textit` commands seem to be ineffective.

2. We see extra comma's on top of the authors' names (rather than next to them for separation) that we could not remove.

3. Could you tell us how the field "Reviewed by" should be filled?

Could you help us with the above-mentioned issues?
We would appreciate your time and help.

### CODE REVIEW

**Comment by rougier** [comment]
Other authors get similar problems and we're investigating.

**Comment by carlito387** [comment]
Hi, I had the same problem for the bold and italic text and managed to solve it by removing the \usepackage[T1]{fontenc} in my article.tex. This package was breaking the RescienceC class and font.

For the commas problem you describe, simply remove the yellow comma in metadata.yaml:
image

Finally, to get a comma separating the before last and last author's names, I added the command `\renewcommand\Authands{, }` (it can also be `\renewcommand\Authands{, and }`) in the Authors block of the rescience.cls, which replaces the initial command `\renewcommand\Authands{\normalfont\sffamily\small}`. @rougier Maybe this can be changed in the generic class, as this is an issue everyone is facing, even the ones that have already made their PR. 

You can look at the changes I made in my PR #25.

**Comment by rougier** [comment]
A PR would be nice yes !

**Comment by MoeinSorkhei** [comment]
> Hi, I had the same problem for the bold and italic text and managed to solve it by removing the \usepackage[T1]{fontenc} in my article.tex. This package was breaking the RescienceC class and font.
> 
> For the commas problem you describe, simply remove the yellow comma in metadata.yaml:
> image
> 
> Finally, to get a comma separating the before last and last author's names, I added the command `\renewcommand\Authands{, }` (it can also be `\renewcommand\Authands{, and }`) in the Authors block of the rescience.cls, which replaces the initial command `\renewcommand\Authands{\normalfont\sffamily\small}`. @rougier Maybe this can be changed in the generic class, as this is an issue everyone is facing, even the ones that have already made their PR.
> 
> You can look at the changes I made in my PR #25.

Hi

**Comment by MoeinSorkhei** [comment]
Hi @carlito387,

Thank you very much for your insightful response!
It perfectly solved the issues.

**Pull request merged**
