### PR TITLE
Add Editorial for the special edition

### PR DESCRIPTION
**Pull request by koustuvsinha**
[Compiled editorial](https://github.com/ReScience/NeurIPS-2019/blob/master/editorial/article.pdf)

### CODE REVIEW

**Comment by koustuvsinha** [comment]
Merging for now.

**Comment by rougier** [comment]
Link to the editorial does not work for me.

**Comment by koustuvsinha** [comment]
@rougier apologies, the link broke after accepting to master. fixed it.

**Comment by rougier** [comment]
Many thanks and sorry for the delay. I'm very late.
For the list of reviewers, you might try to use an alternative font size such as small or footnotesize such that you can maybe fit names on 4 columns. Also, the spacing between rows is quite big, any way to reduce it ?

**Comment by koustuvsinha** [comment]
@rougier reduced the fontsize, does it look better now?

**Comment by rougier** [comment]
Almost ! You should get rid of the indent at the left of the table and some name got cut. Maybe you can keep the fontsize and revert to 3 columns such that names are not spread over two lines. But in any  case, this is very minor comment.

**Comment by koustuvsinha** [comment]
@rougier reverted to 3 columns, looks good but except a few names I guess.

**Pull request merged**
