### PR TITLE
Issue #6: Reorganized files and complemented metadata.yaml file.

### PR DESCRIPTION
**Pull request by aradove**
Updated repository to match instructions. 

There are however a lot of warnings when we compile, and you need to compile twice to get the references right. The pdf output seems to be correct nonetheless.

### CODE REVIEW

**Comment by rougier** [comment]
Warnings and compiling twice is "normal" for latex.

**Comment by aradove** [comment]
True!

Did we manage to fill everything out correctly?

**Comment by rougier** [comment]
Looks good to me. In your bibliography file, you might want to check some the arxiv entries that may be wrongly formatted (while some others are ok). When format is right, the resulting entry in the article is clickable. Same for journal articles, if you had the DOI in the bibtex, it will be clickable in your PDF.

**Comment by aradove** [comment]
> Looks good to me. In your bibliography file, you might want to check some the arxiv entries that may be wrongly formatted (while some others are ok). When format is right, the resulting entry in the article is clickable. Same for journal articles, if you had the DOI in the bibtex, it will be clickable in your PDF.

I don't really understand what you mean. Most entries does have a clickable link, and you can click on a reference to get to the bibliography.

Can you be more specific?

**Comment by rougier** [comment]
I mean in the actual references section. Each item can be made clickable if an url or a doi is provided in the bibliography. Clicking on the link will open the corresponding url/doi.

**Comment by okviman** [comment]
Hi @rougier, our most recent commit now makes all arxiv citations clickable. 

What more should we adjust in order for us to merge?

**Comment by koustuvsinha** [comment]
LGTM!

**Pull request merged**
